Repository confluentinc/ksql, pull requests merged in 2018-08, with the labels that each got.

#1603 Return false for null rows in predicate.
  ksql-engine/src/main/java/io/confluent/ksql/structured/SqlPredicate.java
  ksql-engine/src/test/java/io/confluent/ksql/structured/SqlPredicateTest.java
  ksql-engine/src/test/resources/query-validation-tests/project-filter.json
Labels: enhancement

#1713 Using ksql topic name instead of Kafka topic name in topic map in met…
  ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
  ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
  ksql-engine/src/test/java/io/confluent/ksql/analyzer/AnalyzerTest.java
  ksql-engine/src/test/resources/query-validation-tests/project-filter.json
Labels: bug

#1728 Minor docs fix.
  docs/syntax-reference.rst
Labels: documentation

#1622 Ksql 1029 improve csas/ctas existing stream error message
  ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java
  ksql-engine/src/test/java/io/confluent/ksql/QueryEngineTest.java
  ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
  ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStore.java
  ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java
  ksql-metastore/src/test/java/io/confluent/ksql/metastore/MetastoreTest.java
Labels: user-experience

#1646 Include data source type in the logical plan
  ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/FilterNode.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/OutputNode.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/PlanNode.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/ProjectNode.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/StructuredDataSourceNode.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/plan/OutputNodeTest.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/plan/ProjectNodeTest.java
Labels: bug

#1811 Optimize include for CP quickstart
  docs/includes/ksql-includes.rst
Labels: documentation

#1801 Switching back to good old if statement!
  ksql-engine/src/test/resources/query-validation-tests/project-filter.json
  ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriter.java
Labels: bug
