Repository confluentinc/ksql, pull requests merged in 2018-04, with the labels that each got.

#1025 DOCS-352 - Add info for kafka.core.streams
  docs/installation/cli-config.rst
  docs/installation/server-config/ccloud-ksql.rst
  docs/installation/server-config/config-reference.rst
  docs/installation/server-config/index.rst
  docs/syntax-reference.rst
Labels: documentation

#1098 Docs on configuring KSQL -> SR over HTTPS
  docs-rst/installation/server-config/security.rst
  ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
  ksql-engine/src/test/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactoryTest.java
Labels: documentation

#1141 Minor security docs tweaks
  docs/installation/server-config/security.rst
Labels: documentation

#1135 Formatting for CLI start command
  docs/includes/ksql-includes.rst
  docs/installation/installing.rst
Labels: documentation

#652 Added referential integrity enforcement for streams/tables and queries
  ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
  ksql-common/src/main/java/io/confluent/ksql/util/KsqlReferentialIntegrityException.java
  ksql-common/src/main/java/io/confluent/ksql/util/Pair.java
  ksql-engine/src/main/java/io/confluent/ksql/KsqlContext.java
  ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
  ksql-engine/src/main/java/io/confluent/ksql/QueryEngine.java
  ksql-engine/src/main/java/io/confluent/ksql/analyzer/AggregateAnalyzer.java
  ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DdlCommandExec.java
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java
  ksql-engine/src/main/java/io/confluent/ksql/function/FunctionRegistry.java
  ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/PlanSourceExtractorVisitor.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/JoinNode.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/PlanVisitor.java
  ksql-engine/src/main/java/io/confluent/ksql/util/PersistentQueryMetadata.java
  ksql-engine/src/test/java/io/confluent/ksql/KsqlContextTest.java
  ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java
  ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java
  ksql-engine/src/test/java/io/confluent/ksql/integration/EndToEndIntegrationTest.java
  ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
  ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/PlanSourceExtractorVisitorTest.java
  ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
  ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStore.java
  ksql-metastore/src/main/java/io/confluent/ksql/metastore/MetaStoreImpl.java
  ksql-metastore/src/main/java/io/confluent/ksql/metastore/ReferentialIntegrityTableEntry.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/DefaultTraversalVisitor.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/StatementExecutor.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/StatementExecutorTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
Labels: enhancement

#1109 Ksql 1054 better aggregation with complex expressions
  checkstyle/suppressions.xml
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
  ksql-engine/src/main/java/io/confluent/ksql/structured/SchemaKStream.java
  ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
  ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java
  ksql-engine/src/test/resources/query-validation-tests/sum.json
Labels: bug

#1131 Fix clickstream instructions
  docs/tutorials/basics-local.rst
  docs/tutorials/clickstream-docker.rst
  docs/tutorials/clickstream-local.rst
  docs/tutorials/index.rst
Labels: documentation

#1196 Fix code formatting typo
  docs/installation/installing.rst
Labels: documentation

#1245 Delete empty content
  docs/installation/common-scenarios.rst
  docs/installation/index.rst
Labels: documentation

#1246 Fix link to include
  docs/syntax-reference.rst
Labels: documentation
