Repository confluentinc/ksql, pull requests merged in 2018-03, with the labels that each got.

#856 Updated the default path for logs in KSQL.
  bin/ksql
  bin/ksql-run-class
  bin/ksql-server-start
  config/log4j-file.properties
  debian/confluent-ksql.service
Labels: bug

#933 Use `_confluent-ksql` as prefix for the command topic.
  ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
  ksql-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
  ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
  ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KafkaTopicsList.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/BrokerCompatibilityCheck.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestConfig.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/client/KsqlRestClientTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestConfigTest.java
Labels: bug

#987 KSQL-758-Add an optional properties file for data-gen
  ksql-examples/src/main/resources/datagen.properties
Labels: task

#964 DOCS-353 - Add new CLI config topic
  docs/installation/cli-config.rst
  docs/installation/index.rst
  docs/installation/server-config/index.rst
Labels: documentation

#1026 KSQL-808 - Document RUN SCRIPT command
  docs/syntax-reference.rst
Labels: documentation

#1010 DOCS-357 - Avro and Schema Registry
  docs/faq.rst
  docs/includes/ksql-includes.rst
  docs/installation/server-config/avro-schema.rst
  docs/tutorials/examples.rst
Labels: documentation

#960 KSQL-525 - Security docs
  docs/faq.rst
  docs/installation/index.rst
  docs/installation/server-config/index.rst
  docs/installation/server-config/security.rst
Labels: documentation

#974 DOCS-344 - CLI and Server Installation, Architecture
  docs/faq.rst
  docs/installation/architecture.rst
  docs/installation/client-server.rst
  docs/installation/index.rst
  docs/installation/installing.rst
  docs/installation/server-config/index.rst
  docs/installation/standalone.rst
  docs/syntax-reference.rst
Labels: documentation

#963 Add a page for tuning KSQL in production
  docs/installation/server-config/index.rst
Labels: documentation

#1051 Security Docs tweaks
  docs/installation/server-config/security.rst
Labels: documentation

#1042 Set the clean up policy to compact for non-windowed tables.
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
  ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClient.java
  ksql-engine/src/main/java/io/confluent/ksql/util/KafkaTopicClientImpl.java
  ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java
  ksql-engine/src/test/java/io/confluent/ksql/QueryTranslationTest.java
  ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
  ksql-engine/src/test/java/io/confluent/ksql/integration/JsonFormatTest.java
  ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
  ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
  ksql-engine/src/test/java/io/confluent/ksql/util/FakeKafkaTopicClient.java
  ksql-engine/src/test/java/io/confluent/ksql/util/KafkaTopicClientTest.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/BrokerCompatibilityCheck.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/BrokerCompatibilityCheckTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/mock/MockKafkaTopicClient.java
Labels: bug

#1072 Doc improvements for Syntax guilde.
  docs/syntax-reference.rst
Labels: documentation

#1070 Tests fixes.
  ksql-engine/src/test/java/io/confluent/ksql/integration/WindowingIntTest.java
  ksql-engine/src/test/java/io/confluent/ksql/util/FakeKafkaTopicClient.java
Labels: task
