Repository confluentinc/ksql, pull requests merged in 2018-06, with the labels that each got.

#1369 Using the kafka topic name in delete topic message.
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java
Labels: user-experience

#1368 Using ExpressionTypeManager to detect the types for function look up.
  ksql-engine/src/main/java/io/confluent/ksql/codegen/CodeGenRunner.java
  ksql-engine/src/main/java/io/confluent/ksql/codegen/FunctionArguments.java
  ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/AggregateNode.java
  ksql-engine/src/main/java/io/confluent/ksql/util/ExpressionTypeManager.java
  ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
  ksql-engine/src/test/java/io/confluent/ksql/util/ExpressionTypeManagerTest.java
Labels: enhancement

#1383 Using Connect data format in KSQL.
  ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
  ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
  ksql-common/src/test/java/io/confluent/ksql/GenericRowTest.java
  ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
  ksql-engine/src/main/java/io/confluent/ksql/codegen/SqlToJavaVisitor.java
  ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topk/TopkKudaf.java
  ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topkdistinct/TopkDistinctAggFunctionFactory.java
  ksql-engine/src/main/java/io/confluent/ksql/function/udaf/topkdistinct/TopkDistinctKudaf.java
  ksql-engine/src/main/java/io/confluent/ksql/physical/PhysicalPlanBuilder.java
  ksql-engine/src/main/java/io/confluent/ksql/util/GenericRowValueTypeEnforcer.java
  ksql-engine/src/test/java/io/confluent/ksql/codegen/SqlToJavaVisitorTest.java
  ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/DoubleTopkKudafTest.java
  ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/IntTopkKudafTest.java
  ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/LongTopkKudafTest.java
  ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topk/StringTopkKudafTest.java
  ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topkdistinct/DoubleTopkDistinctKudafTest.java
  ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topkdistinct/IntTopkDistinctKudafTest.java
  ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topkdistinct/LongTopkDistinctKudafTest.java
  ksql-engine/src/test/java/io/confluent/ksql/function/udaf/topkdistinct/StringTopkDistinctKudafTest.java
  ksql-engine/src/test/java/io/confluent/ksql/integration/IntegrationTestHarness.java
  ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
  ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedTableTest.java
  ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
  ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
  ksql-engine/src/test/java/io/confluent/ksql/structured/SqlPredicateTest.java
  ksql-engine/src/test/java/io/confluent/ksql/util/OrderDataProvider.java
  ksql-engine/src/test/java/io/confluent/ksql/util/PageViewDataProvider.java
  ksql-engine/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
  ksql-engine/src/test/java/io/confluent/ksql/util/TopicConsumer.java
  ksql-engine/src/test/java/io/confluent/ksql/util/UserDataProvider.java
  ksql-engine/src/test/resources/query-validation-tests/extract-json-field.json
  ksql-engine/src/test/resources/query-validation-tests/hopping-windows.json
  ksql-engine/src/test/resources/query-validation-tests/sum.json
  ksql-engine/src/test/resources/query-validation-tests/topk-distinct.json
  ksql-engine/src/test/resources/query-validation-tests/topk-group-by.json
  ksql-engine/src/test/resources/query-validation-tests/tumbling-windows.json
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/client/KsqlRestClient.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriter.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/client/KsqlRestClientTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/StreamedQueryResourceTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/QueryStreamWriterTest.java
  ksql-serde/src/main/java/io/confluent/ksql/serde/avro/KsqlGenericRowAvroDeserializer.java
  ksql-serde/src/main/java/io/confluent/ksql/serde/avro/KsqlGenericRowAvroSerializer.java
  ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java
  ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonSerializer.java
  ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonTopicSerDe.java
  ksql-serde/src/main/java/io/confluent/ksql/serde/util/SerdeUtils.java
  ksql-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlGenericRowAvroDeserializerTest.java
  ksql-serde/src/test/java/io/confluent/ksql/serde/avro/KsqlGenericRowAvroSerializerTest.java
  ksql-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonDeserializerTest.java
  ksql-serde/src/test/java/io/confluent/ksql/serde/json/KsqlJsonSerializerTest.java
  ksql-serde/src/test/java/io/confluent/ksql/serde/util/SerdeUtilsTest.java
Labels: enhancement

#1410 Added query rewrite feature using AST.
  checkstyle/suppressions.xml
  ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriter.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStreamAsSelect.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DefaultAstVisitor.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/HoppingWindowExpression.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/SessionWindowExpression.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/SimpleGroupBy.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Table.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/TumblingWindowExpression.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Window.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/WindowExpression.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/rewrite/StatementRewriterTest.java
Labels: enhancement

#1430 Updated AST builder to handle dot notation.
  checkstyle/suppressions.xml
  ksql-metastore/src/test/java/io/confluent/ksql/util/MetaStoreFixture.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriter.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStream.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateStreamAsSelect.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTable.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/CreateTableAsSelect.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropTable.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/InsertInto.java
  ksql-parser/src/main/java/io/confluent/ksql/util/DataSourceExtractor.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/rewrite/StatementRewriterTest.java
Labels: enhancement

#1478 Use ':' for struct field reference.
  ksql-common/src/main/java/io/confluent/ksql/util/KsqlConstants.java
  ksql-engine/src/test/java/io/confluent/ksql/util/ExpressionTypeManagerTest.java
  ksql-engine/src/test/resources/query-validation-tests/more-complex-struct.json
  ksql-engine/src/test/resources/query-validation-tests/simple-struct.json
  ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
  ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/ExpressionFormatter.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/StatementRewriter.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DefaultAstVisitor.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ExpressionRewriter.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ExpressionTreeRewriter.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/LambdaExpression.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/ExpressionFormatterTest.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/rewrite/StatementRewriteForStructTest.java
  ksql-serde/src/main/java/io/confluent/ksql/serde/json/KsqlJsonDeserializer.java
Labels: enhancement

#1495 Pass schema registry client configs onto the schema registry client
  docs/installation/server-config/security.rst
  ksql-engine/src/main/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactory.java
  ksql-engine/src/test/java/io/confluent/ksql/schema/registry/KsqlSchemaRegistryClientFactoryTest.java
Labels: enhancement

#1502 Rename DdlCommandTask to KsqlStatementTask in KsqlResources class.
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
Labels: Code Quality
