Repository confluentinc/ksql, pull requests merged in 2018-05, with the labels that each got.

#1250 DOCS-419 - KSQL doc should link to syntax reference etc
  docs/index.rst
Labels: documentation

#1259 Change GIT URL to HTTPS
  docs/tutorials/basics-docker.rst
Labels: documentation

#1275 KSQL-945 - Fix KSQL left-hand nav
  docs/index.rst
Labels: documentation

#1276 Fix doc build issues
  docs/api.rst
  docs/installation/index.rst
  docs/installation/server-config/index.rst
  docs/key-constraints.rst
  docs/syntax-reference.rst
Labels: documentation

#1257 Clarify how to install KSQL
  docs/installation/installing.rst
  docs/installation/server-config/security.rst
  docs/installation/upgrading.rst
  docs/operations.rst
Labels: documentation, user-experience

#1114 Struct Data Type(Part-1): New struct type, DDL statements and Describe
  ksql-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
  ksql-common/src/main/java/io/confluent/ksql/util/SchemaUtil.java
  ksql-common/src/test/java/io/confluent/ksql/util/SchemaUtilTest.java
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/AbstractCreateStreamCommand.java
  ksql-engine/src/main/java/io/confluent/ksql/util/AvroUtil.java
  ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java
  ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
  ksql-engine/src/test/resources/query-validation-tests/max-group-by.json
  ksql-engine/src/test/resources/query-validation-tests/min-group-by.json
  ksql-engine/src/test/resources/query-validation-tests/sum.json
  ksql-engine/src/test/resources/query-validation-tests/topk-distinct.json
  ksql-engine/src/test/resources/query-validation-tests/topk-group-by.json
  ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
  ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/DefaultTraversalVisitor.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/ExpressionFormatter.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/rewrite/SetParentVisitor.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Array.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/AstVisitor.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DefaultAstVisitor.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DefaultTraversalVisitor.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ExpressionRewriter.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/ExpressionTreeRewriter.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Map.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Node.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/PrimitiveType.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Struct.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/TableElement.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/Type.java
  ksql-parser/src/main/java/io/confluent/ksql/util/TypeUtil.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/ExpressionFormatterTest.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/KsqlParserTest.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/util/TypeUtilTest.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/QueryDescription.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
Labels: enhancement

#1277 Ksql 1217 optionally delete kafka topic with drop statement
  checkstyle/suppressions.xml
  docs/syntax-reference.rst
  ksql-cli/src/test/java/io/confluent/ksql/CliTest.java
  ksql-engine/src/main/java/io/confluent/ksql/KsqlEngine.java
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DropSourceCommand.java
  ksql-engine/src/test/java/io/confluent/ksql/KsqlEngineTest.java
  ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java
  ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/DropSourceCommandTest.java
  ksql-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
  ksql-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropStream.java
  ksql-parser/src/main/java/io/confluent/ksql/parser/tree/DropTable.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
Labels: enhancement
