Repository confluentinc/ksql, pull requests merged in 2019-04, with the labels that each got.

#2503 KLIP-1: Improve UDF Interfaces
  design-proposals/README.md
  design-proposals/klip-1-improve-udf-interfaces.md
Labels: design-proposal

#2683 PRINT does not deserialize a DELIMITED topic with one integer column
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/TopicStream.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/TopicStreamTest.java
Labels: bug

#2693 KLIP-4: insert into semantics to produce raw data
  design-proposals/README.md
  design-proposals/klip-2-produce-data.md
  design-proposals/klip-template.md
Labels: design-proposal, user-experience

#2698 Don't do unnecessary rebuild of sink topic serde for avro
  ksql-engine/src/main/java/io/confluent/ksql/analyzer/Analyzer.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNode.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlStructuredDataOutputNodeTest.java
  ksql-engine/src/test/resources/query-validation-tests/insert-into.json
Labels: bug

#2719 fix race condition in RestApiTest shutdown: fixes flaky test in 5.0.x
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
Labels: test-stability

#2677 Add support for structs in UDF parameters
  docs/developer-guide/udf.rst
  ksql-common/src/test/java/io/confluent/ksql/function/UdfIndexTest.java
  ksql-engine/src/main/java/io/confluent/ksql/function/UdfCompiler.java
  ksql-engine/src/main/java/io/confluent/ksql/function/UdfLoader.java
  ksql-engine/src/test/java/io/confluent/ksql/codegen/CodeGenRunnerTest.java
  ksql-engine/src/test/java/io/confluent/ksql/function/UdfCompilerTest.java
  ksql-engine/src/test/java/io/confluent/ksql/function/udf/TestUdf.java
  ksql-engine/src/test/resources/query-validation-tests/create-struct.json
  ksql-engine/src/test/resources/query-validation-tests/struct-udfs.json
  ksql-parser/src/main/java/io/confluent/ksql/schema/ksql/LogicalSchemas.java
  ksql-parser/src/test/java/io/confluent/ksql/schema/ksql/LogicalSchemasTest.java
  ksql-udf/src/main/java/io/confluent/ksql/function/udf/UdfParameter.java
Labels: data-accessibility

#2739 support udf imports with no package (fixes #2721 targets 5.2.x)
  ksql-engine/src/main/java/io/confluent/ksql/function/UdfCompiler.java
  ksql-engine/src/main/java/io/confluent/ksql/function/UdfTemplate.java
  ksql-engine/src/test/java/TestUdfWithNoPackage.java
Labels: bug, user-defined-functions
