Repository confluentinc/ksql, pull requests merged in 2019-06, with the labels that each got.

#2945 Added clarification to docs for PARTITION BY
  docs/developer-guide/syntax-reference.rst
Labels: documentation

#3010 docs: Updated the changelog for 5.3.
  docs/changelog.rst
  docs/installation/upgrading.rst
Labels: documentation

#2951 docs: Klip-5: Internal Schemas for KSQL Engine
  design-proposals/klip-5-internal-schemas-for-KSQL-engine.md
Labels: design-proposal

#3000 feat: Add REST and Websocket authorization hooks and interface
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/filters/KsqlAuthorizationFilter.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/Errors.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/security/KsqlAuthorizationProvider.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/security/KsqlAuthorizer.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/security/KsqlDefaultSecurityExtension.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/security/KsqlSecurityExtension.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/AuthorizationFunctionalTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/MockKsqlSecurityExtension.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestIntegrationTestUtil.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/filters/KsqlAuthorizationFilterTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
  ksql-test-util/src/main/java/io/confluent/ksql/test/util/EmbeddedSingleNodeKafkaCluster.java
Labels: security

#3022 fix(test runner): pass only source topic inputs to topology
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TopologyTestDriverContainer.java
  ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/KsqlTestingToolTest.java
  ksql-functional-tests/src/test/resources/test-runner/correct/aggregate/input.json
  ksql-functional-tests/src/test/resources/test-runner/correct/aggregate/output.json
  ksql-functional-tests/src/test/resources/test-runner/correct/aggregate/statements.sql
  ksql-functional-tests/src/test/resources/test-runner/correct/join/input.json
  ksql-functional-tests/src/test/resources/test-runner/correct/join/output.json
  ksql-functional-tests/src/test/resources/test-runner/correct/join/statements.sql
  ksql-functional-tests/src/test/resources/test-runner/correct/multi_insert_into/input.json
  ksql-functional-tests/src/test/resources/test-runner/correct/multi_insert_into/output.json
  ksql-functional-tests/src/test/resources/test-runner/correct/multi_insert_into/statements.sql
  ksql-functional-tests/src/test/resources/test-runner/correct/simple_project_filter/input.json
  ksql-functional-tests/src/test/resources/test-runner/correct/simple_project_filter/output.json
  ksql-functional-tests/src/test/resources/test-runner/correct/simple_project_filter/statements.sql
  ksql-functional-tests/src/test/resources/test-runner/incorrect/empty_input/input.json
  ksql-functional-tests/src/test/resources/test-runner/incorrect/empty_input/output.json
  ksql-functional-tests/src/test/resources/test-runner/incorrect/empty_input/statements.sql
  ksql-functional-tests/src/test/resources/test-runner/incorrect/empty_output/input.json
  ksql-functional-tests/src/test/resources/test-runner/incorrect/empty_output/output.json
  ksql-functional-tests/src/test/resources/test-runner/incorrect/empty_output/statements.sql
  ksql-functional-tests/src/test/resources/test-runner/incorrect/expected_mismatch/input.json
  ksql-functional-tests/src/test/resources/test-runner/incorrect/expected_mismatch/output.json
  ksql-functional-tests/src/test/resources/test-runner/incorrect/expected_mismatch/statements.sql
  ksql-functional-tests/src/test/resources/test-runner/incorrect/incorrect_input_format/input.json
  ksql-functional-tests/src/test/resources/test-runner/incorrect/incorrect_input_format/output.json
  ksql-functional-tests/src/test/resources/test-runner/incorrect/incorrect_input_format/statements.sql
  ksql-functional-tests/src/test/resources/test-runner/incorrect/missing_field_in_output/input.json
  ksql-functional-tests/src/test/resources/test-runner/incorrect/missing_field_in_output/output.json
  ksql-functional-tests/src/test/resources/test-runner/incorrect/missing_field_in_output/statements.sql
Labels: bug

#3027 fix: `SqlFormatter` now handles windows
  ksql-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
  ksql-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
Labels: bug
