Repository confluentinc/ksql, pull requests merged in 2019-08, with the labels that each got.

#3111 fix: add ksql-functional-tests to the ksql package
  ksql-package/pom.xml
Labels: bug

#3176 fix: default timestamp extractor override is not working
  ksql-common/src/main/java/io/confluent/ksql/util/timestamp/MetadataTimestampExtractionPolicy.java
  ksql-common/src/main/java/io/confluent/ksql/util/timestamp/TimestampExtractionPolicyFactory.java
  ksql-common/src/test/java/io/confluent/ksql/util/timestamp/MetadataTimestampExtractionPolicyTest.java
  ksql-common/src/test/java/io/confluent/ksql/util/timestamp/TimestampExtractionPolicyFactoryTest.java
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CommandFactories.java
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateSourceCommand.java
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateStreamCommand.java
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/CreateTableCommand.java
  ksql-engine/src/main/java/io/confluent/ksql/ddl/commands/DdlCommandFactory.java
  ksql-engine/src/main/java/io/confluent/ksql/engine/EngineContext.java
  ksql-engine/src/main/java/io/confluent/ksql/engine/EngineExecutor.java
  ksql-engine/src/main/java/io/confluent/ksql/engine/QueryEngine.java
  ksql-engine/src/main/java/io/confluent/ksql/planner/LogicalPlanner.java
  ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CommandFactoriesTest.java
  ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateSourceCommandTest.java
  ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateStreamCommandTest.java
  ksql-engine/src/test/java/io/confluent/ksql/ddl/commands/CreateTableCommandTest.java
  ksql-engine/src/test/java/io/confluent/ksql/physical/PhysicalPlanBuilderTest.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/PlanSourceExtractorVisitorTest.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/plan/AggregateNodeTest.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/plan/JoinNodeTest.java
  ksql-engine/src/test/java/io/confluent/ksql/planner/plan/KsqlBareOutputNodeTest.java
  ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKGroupedTableTest.java
  ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKStreamTest.java
  ksql-engine/src/test/java/io/confluent/ksql/structured/SchemaKTableTest.java
  ksql-engine/src/test/java/io/confluent/ksql/structured/SelectValueMapperTest.java
  ksql-engine/src/test/java/io/confluent/ksql/structured/SqlPredicateTest.java
  ksql-engine/src/test/java/io/confluent/ksql/testutils/AnalysisTestUtil.java
  ksql-functional-tests/src/test/resources/query-validation-tests/timestamp-extractor.json
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/entity/KsqlRequest.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/entity/KsqlRequestTest.java
Labels: bug

#3186 fix: incorrect SR authorization message is displayed
  ksql-common/src/main/java/io/confluent/ksql/links/DocumentationLinks.java
  ksql-engine/src/main/java/io/confluent/ksql/engine/InsertValuesExecutor.java
  ksql-engine/src/main/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplier.java
  ksql-engine/src/main/java/io/confluent/ksql/util/AvroUtil.java
  ksql-engine/src/test/java/io/confluent/ksql/engine/InsertValuesExecutorTest.java
  ksql-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegistryTopicSchemaSupplierTest.java
  ksql-engine/src/test/java/io/confluent/ksql/util/AvroUtilTest.java
  ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/KsqlTestingToolTest.java
Labels: bug, user-experience

#3180 refactor: Run QTT using the testing tool
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/RecordNode.java
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/TestCaseNode.java
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/model/TopicNode.java
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/avro/ValueSpecAvroSerdeSupplier.java
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/FakeKafkaService.java
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCase.java
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutorUtil.java
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/Topic.java
  ksql-functional-tests/src/test/java/io/confluent/ksql/test/EndToEndEngineTestUtil.java
  ksql-functional-tests/src/test/java/io/confluent/ksql/test/SchemaTranslationTest.java
  ksql-functional-tests/src/test/resources/query-validation-tests/elements.json
  ksql-functional-tests/src/test/resources/query-validation-tests/session-windows.json
Labels: Code Quality

#3198 refactor: Improve error message for testing tool
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestCase.java
  ksql-functional-tests/src/test/java/io/confluent/ksql/test/tools/TestCaseTest.java
Labels: user-experience

#3182 Add anchor
  docs/tutorials/basics-local.rst
Labels: documentation

#3196 docs: Improve testing tool docs
  docs/developer-guide/ksql-testing-tool.rst
Labels: documentation

#3236 fix: fix a bug in testing tool serde
  ksql-functional-tests/src/main/java/io/confluent/ksql/test/serde/avro/ValueSpecAvroSerdeSupplier.java
  ksql-functional-tests/src/test/resources/test-runner/correct/multi_join/input.json
  ksql-functional-tests/src/test/resources/test-runner/correct/multi_join/output.json
  ksql-functional-tests/src/test/resources/test-runner/correct/multi_join/statements.sql
Labels: bug
