Repository confluentinc/ksql, pull requests merged in 2020-07, with the labels that each got.

#5739 feat: add syntax for suppression
  ksqldb-common/src/main/java/io/confluent/ksql/parser/ResultMaterialization.java
  ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/Analysis.java
  ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/ImmutableAnalysis.java
  ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/PullQueryValidator.java
  ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/PushQueryValidator.java
  ksqldb-engine/src/main/java/io/confluent/ksql/analyzer/RewrittenAnalysis.java
  ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/AnalysisTest.java
  ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/PullQueryValidatorTest.java
  ksqldb-engine/src/test/java/io/confluent/ksql/analyzer/PushQueryValidatorTest.java
  ksqldb-engine/src/test/java/io/confluent/ksql/engine/rewrite/StatementRewriterTest.java
  ksqldb-parser/src/main/antlr4/io/confluent/ksql/parser/SqlBase.g4
  ksqldb-parser/src/main/java/io/confluent/ksql/parser/AstBuilder.java
  ksqldb-parser/src/main/java/io/confluent/ksql/parser/SqlFormatter.java
  ksqldb-parser/src/main/java/io/confluent/ksql/parser/tree/Query.java
  ksqldb-parser/src/test/java/io/confluent/ksql/parser/AstBuilderTest.java
  ksqldb-parser/src/test/java/io/confluent/ksql/parser/SqlFormatterTest.java
  ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/ParserModelTest.java
  ksqldb-parser/src/test/java/io/confluent/ksql/parser/tree/QueryTest.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/PullQueryExecutorTest.java
Labels: enhancement

#5851 chore: do not try to re-register schema multiple times on failure
  ksqldb-engine/src/main/java/io/confluent/ksql/query/MissingTopicClassifier.java
  ksqldb-streams/src/main/java/io/confluent/ksql/execution/streams/RegisterSchemaCallback.java
  ksqldb-streams/src/test/java/io/confluent/ksql/execution/streams/RegisterSchemaCallbackTest.java
Labels: blocker

#5865 chore: dont list all topics to determine single topic existence (MINOR)
  ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
  ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
Labels: P0

#5895 fix: adds a handler to gracefully shutdown
  ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/ConnectExecutable.java
  ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/Executable.java
  ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
  ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlServerMain.java
  ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/MultiExecutable.java
  ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/StandaloneExecutor.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/ConnectIntegrationTest.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlServerMainTest.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/MultiExecutableTest.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorFunctionalTest.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/StandaloneExecutorTest.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
Labels: blocker
