Repository confluentinc/ksql, pull requests merged in 2020-08, with the labels that each got.

#5921 chore: isTopicExists should not throw if topic has denied authorization
  ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
  ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
Labels: bug

#5476 feat: Add consumer offsets to DESCRIBE EXTENDED
  ksqldb-api-client/src/test/java/io/confluent/ksql/api/client/ClientTest.java
  ksqldb-cli/src/main/java/io/confluent/ksql/cli/console/Console.java
  ksqldb-cli/src/test/java/io/confluent/ksql/cli/console/ConsoleTest.java
  ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
  ksqldb-common/src/main/java/io/confluent/ksql/util/QueryApplicationId.java
  ksqldb-common/src/test/java/QueryApplicationIdTest.java
  ksqldb-engine/src/main/java/io/confluent/ksql/exception/KsqlGroupAuthorizationException.java
  ksqldb-engine/src/main/java/io/confluent/ksql/query/QueryExecutor.java
  ksqldb-engine/src/main/java/io/confluent/ksql/services/DefaultServiceContext.java
  ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaConsumerGroupClientImpl.java
  ksqldb-engine/src/main/java/io/confluent/ksql/services/KafkaTopicClientImpl.java
  ksqldb-engine/src/main/java/io/confluent/ksql/services/LazyServiceContext.java
  ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedKafkaConsumerGroupClient.java
  ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedKafkaTopicClient.java
  ksqldb-engine/src/main/java/io/confluent/ksql/services/SandboxedServiceContext.java
  ksqldb-engine/src/test/java/io/confluent/ksql/integration/KafkaConsumerGroupClientTest.java
  ksqldb-engine/src/test/java/io/confluent/ksql/schema/ksql/inference/SchemaRegisterInjectorTest.java
  ksqldb-engine/src/test/java/io/confluent/ksql/services/FakeKafkaConsumerGroupClient.java
  ksqldb-engine/src/test/java/io/confluent/ksql/services/FakeKafkaTopicClient.java
  ksqldb-engine/src/test/java/io/confluent/ksql/services/KafkaTopicClientImplTest.java
  ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedKafkaTopicClientTest.java
  ksqldb-engine/src/test/java/io/confluent/ksql/services/SandboxedServiceContextTest.java
  ksqldb-engine/src/test/java/io/confluent/ksql/services/TestServiceContext.java
  ksqldb-execution/src/main/java/io/confluent/ksql/services/KafkaConsumerGroupClient.java
  ksqldb-execution/src/main/java/io/confluent/ksql/services/KafkaTopicClient.java
  ksqldb-execution/src/main/java/io/confluent/ksql/services/ServiceContext.java
  ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/TestExecutor.java
  ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/stubs/StubKafkaConsumerGroupClient.java
  ksqldb-functional-tests/src/main/java/io/confluent/ksql/test/tools/stubs/StubKafkaTopicClient.java
  ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/entity/SourceDescriptionFactory.java
  ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/DescribeConnectorExecutor.java
  ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListSourceExecutor.java
  ksqldb-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/ListTopicsExecutor.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionFactoryTest.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/ListSourceExecutorTest.java
  ksqldb-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
  ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/ConsumerPartitionOffsets.java
  ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryOffsetSummary.java
  ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/QueryTopicOffsetSummary.java
  ksqldb-rest-model/src/main/java/io/confluent/ksql/rest/entity/SourceDescription.java
  ksqldb-rest-model/src/test/java/io/confluent/ksql/rest/entity/SourceDescriptionTest.java
Labels: enhancement

#6018 fix: set restarted query as healthy during a time threshold
  ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
  ksqldb-engine/src/main/java/io/confluent/ksql/engine/QueryMonitor.java
  ksqldb-engine/src/main/java/io/confluent/ksql/internal/QueryStateListener.java
  ksqldb-engine/src/main/java/io/confluent/ksql/util/QueryMetadata.java
  ksqldb-engine/src/test/java/io/confluent/ksql/engine/QueryMonitorTest.java
  ksqldb-engine/src/test/java/io/confluent/ksql/internal/QueryStateListenerTest.java
  ksqldb-engine/src/test/java/io/confluent/ksql/util/QueryMetadataTest.java
Labels: P0, bug

#6094 chore: disable suppress by default
  ksqldb-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
  ksqldb-engine/src/test/java/io/confluent/ksql/planner/LogicalPlannerTest.java
  ksqldb-functional-tests/src/test/resources/query-validation-tests/suppress.json
  ksqldb-functional-tests/src/test/resources/sql-tests/query-upgrades/filters.sql
Labels: blocker
