Repository confluentinc/ksql, pull requests merged in 2020-01, with the labels that each got.

#4184 refactor: inject a KsqlSecurityContext to REST requests
  ksql-engine/src/main/java/io/confluent/ksql/security/KsqlSecurityContext.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/KsqlRestApplication.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/context/KsqlSecurityContextBinder.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/context/KsqlSecurityContextBinderFactory.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/HealthCheckResource.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/services/ServerInternalKsqlClient.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/KsqlRestApplicationTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/TestKsqlRestApp.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/RecoveryTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/context/KsqlSecurityContextBinderFactoryTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/KsqlResourceTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/services/ServerInternalKsqlClientTest.java
Labels: P0, refactor

#4186 feat: add a KSQL cache for Kafka authorization validator
  ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
  ksql-engine/src/main/java/io/confluent/ksql/security/KsqlAccessValidator.java
  ksql-engine/src/main/java/io/confluent/ksql/security/KsqlAuthorizationValidator.java
  ksql-engine/src/main/java/io/confluent/ksql/security/KsqlAuthorizationValidatorFactory.java
  ksql-engine/src/main/java/io/confluent/ksql/security/KsqlAuthorizationValidatorImpl.java
  ksql-engine/src/main/java/io/confluent/ksql/security/KsqlBackendAccessValidator.java
  ksql-engine/src/main/java/io/confluent/ksql/security/KsqlCacheAccessValidator.java
  ksql-engine/src/test/java/io/confluent/ksql/security/KsqlAuthorizationValidatorFactoryTest.java
  ksql-engine/src/test/java/io/confluent/ksql/security/KsqlAuthorizationValidatorImplTest.java
  ksql-engine/src/test/java/io/confluent/ksql/security/KsqlBackendAccessValidatorTest.java
  ksql-engine/src/test/java/io/confluent/ksql/security/KsqlCacheAccessValidatorTest.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/computation/DistributingExecutor.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/execution/RequestHandler.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/KsqlResource.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/computation/DistributingExecutorTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/execution/RequestHandlerTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
Labels: P0

#4187 feat: enable Kafla ACL authorization checks for Pull Queries
  ksql-cli/src/test/java/io/confluent/ksql/cli/CliTest.java
  ksql-common/src/main/java/io/confluent/ksql/config/ImmutableProperties.java
  ksql-common/src/main/java/io/confluent/ksql/util/KsqlConfig.java
  ksql-functional-tests/src/test/java/io/confluent/ksql/test/rest/RestQueryTranslationTest.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResource.java
  ksql-rest-app/src/main/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpoint.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/PullQueryFunctionalTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/integration/RestApiTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/StreamedQueryResourceTest.java
  ksql-rest-app/src/test/java/io/confluent/ksql/rest/server/resources/streaming/WSQueryEndpointTest.java
Labels: P0

#4069 docs: klip-15 New client and API
  design-proposals/klip-15-new-api-and-client.md
Labels: design-proposal

#4022 docs: KLIP 12 - Implement High-Availability for Pull queries
  design-proposals/klip-12-pull-high-availability.md
Labels: P0, design-proposal

#4272 fix: add ksql-test-runner deps to ksql package lib
  ksql-package/pom.xml
  ksql-package/src/assembly/package.xml
Labels: blocker, bug

#4373 fix: remove deprecated Acl API
  ksql-engine/src/test/java/io/confluent/ksql/integration/SecureIntegrationTest.java
Labels: bug
